"""Per-call-site wrappers: one function per operation in the Pi0 forward pass.

Each wrapper owns the tile configuration for its call site, compiles the kernel
once per shape, and calls it. Kernels are shared between call sites; configs are
not -- the same GEMM at M=51 and M=768 wants different tiles and a different
warp-specialization setting, which is why some kernels appear here twice through
two variants.

Every config below came from a sweep at the call site's real shape, measured
inside a CUDA graph with cold weights (`autotune.sweep_kernel`, in this
package). They are not defaults and not guesses: three of them were wrong in
ways an eager benchmark could not see, costing 2.4x on one kernel. Re-tune
through `autotune.sweep_kernel` after any shape change, and pass `correct=` --
`kernels.tl_scaled_gate` is numerically sensitive to its tiling and some
tilings produce garbage rather than failing, so timing alone will happily rank
a wrong config first.

Shapes are passed through unpadded. TileLang masks out-of-bounds rows, reduction
columns and output columns exactly as Triton's masks do, so nothing here pads a
buffer; wrappers hand the ragged tensors straight to the kernel and let it write
its destination in place.

Constraints that bite
---------------------

Things that fail quietly, or fail far from their cause:

- `tl_scaled_gate`'s tile config is locked. Correctness there is
  tiling-dependent; some tilings, BLOCK_M=32 among them, produce garbage rather
  than an error. Re-validate numerically after any re-tune.
- The gated-FFN kernels require warp specialization. The dual GEMM reuses one
  shared tile across the two weight stages, which the no-WS pipeline planner
  rejects at compile time. An autotuner sweeping the flag must tolerate that.
- Every expression inside a `T.Pipelined` body must be inlined. A named
  temporary lowers to a bind statement the warp-specialization role pass cannot
  classify, and the compile aborts with an internal check failure.
- A fully out-of-bounds TMA box reads garbage, not zeros. Only the tail of a box
  that starts in bounds is zero-filled. FlashDecoding shrinks its split count
  until no split starts past the key count for exactly this reason; the failure
  mode is NaNs that the running-max update then hides.
- The FlashDecoding combine tile must stay <= 4, and the split tile must be 64.
  Smaller split tiles hit a fragment-layout conflict that fails to lower.
- Nothing may allocate inside the graph. Workspaces come from the allocator the
  runner injects through `make_wrappers`, which freezes after warmup, so a
  request warmup did not cover raises instead of allocating during capture.
- Do not edit this file while a benchmark or profiling job is running. TileLang
  re-reads the source at compile time, so saving a shorter file mid-run makes
  the compile fail with an out-of-range line number.
"""
from __future__ import annotations

from functools import partial

import torch

from flash_vla.runtime.ops import OpSpec, gemm

from .kernels import base as kernels
from .kernels import attention as _attention

_CACHE: dict = {}


def fresh_scratch(role: str, shape, dtype, device) -> torch.Tensor:
    """The default workspace allocator: a new zeroed tensor per call.

    Only for calling a wrapper as a free function outside a runner. A runner
    injects its own allocator through `make_wrappers`, which allocates each
    workspace once and freezes before capture.
    """
    del role
    return torch.zeros(shape, dtype=dtype, device=device)


def _compiled(kernel, **const):
    """Compile `kernel` for one shape and config, memoized on both.

    Keyed on `kernel.tl_name` rather than the kernel object, which TileLang
    leaves unhashable. The name distinguishes the two variants of a shared body,
    so a WS-on and a WS-off call site never collide.
    """
    key = (kernel.tl_name, tuple(sorted(const.items())))
    compiled = _CACHE.get(key)
    if compiled is None:
        compiled = kernel.compile(**const)
        _CACHE[key] = compiled
    return compiled


# ---------------------------------------------------------------------------
# Decoder (18 layers x 10 diffusion steps, M = chunk + 1 = 51)
#
# Every shape here is under one wave, so these are latency-bound rather than
# compute-bound: the configs favour occupancy and pipeline depth over big tiles,
# and warp specialization is off wherever the kernel allows it.
# ---------------------------------------------------------------------------
_DEC_STATE_PROJ = dict(BLOCK_M=16, BLOCK_N=64, BLOCK_K=32, NUM_STAGES=2, THREADS=128)
_DEC_ACTION_IN = dict(BLOCK_M=16, BLOCK_N=64, BLOCK_K=32, NUM_STAGES=2, THREADS=128)
_DEC_ACTION_MLP = dict(BLOCK_M=16, BLOCK_N=64, BLOCK_K=128, NUM_STAGES=3, THREADS=128)
_DEC_QKV = dict(BLOCK_M=64, BLOCK_N=32, BLOCK_K=128, NUM_STAGES=4, THREADS=128)
_DEC_SCORES = dict(BLOCK_M=16, BLOCK_N=32, BLOCK_K=64, NUM_STAGES=5, THREADS=128)
_DEC_SOFTMAX = dict(BLOCK_M=1, THREADS=256)
_DEC_ATTN_V = dict(BLOCK_M=32, BLOCK_N=32, BLOCK_K=256, NUM_STAGES=4, THREADS=128)
_DEC_RESIDUAL = dict(BLOCK_M=16, BLOCK_N=32, BLOCK_K=256, NUM_STAGES=4, THREADS=128)
_DEC_GATE = dict(BLOCK_M=64, BLOCK_N=32, BLOCK_K=256, NUM_STAGES=3, THREADS=128)
_DEC_OUT_PROJ = dict(BLOCK_M=16, BLOCK_N=32, BLOCK_K=256, NUM_STAGES=3, THREADS=128)
_DEC_RMS = dict(BLOCK_M=2, BLOCK_K=256, THREADS=128)

DECODER_HEADS = 8


def _rms_factor(x, out, cfg=_DEC_RMS):
    """Write rsqrt(mean(x^2)+eps) into `out`, which the consuming GEMM then scales by."""
    M, K = x.shape
    _compiled(kernels.tl_rms_factor, M=M, K=K, **cfg)(x, out)
    return out


def action_expert_state_proj(x, weight, bias, out):
    """out = x @ weight + bias, for the single state token (upstream matmul_1_32_1024_bias)."""
    _compiled(kernels.tl_matmul_bias, M=1, N=weight.shape[1], K=weight.shape[0],
              **_DEC_STATE_PROJ)(x.view(1, -1), weight, bias, out)
    return out


def action_expert_action_in_proj(x, weight, bias, out):
    """out = silu(x @ weight + bias) (upstream matmul_k_32_1024_bias_silu)."""
    M, K = x.shape
    kfn = _compiled(kernels.tl_matmul_bias_silu, M=M, N=weight.shape[1], K=K, **_DEC_ACTION_IN)
    out.copy_(kfn(x, weight, bias))
    return out


def action_expert_action_mlp(x, weight, bias, out):
    """out = x @ weight + bias (upstream matmul_k_1024_1024_bias)."""
    M, K = x.shape
    _compiled(kernels.tl_matmul_bias, M=M, N=weight.shape[1], K=K,
              **_DEC_ACTION_MLP)(x, weight, bias, out)
    return out


def action_expert_norm_qkv_rope(x, scale, weight_qkv, bias, rope, Q, K, V, norm_factor):
    """RMS-scale x, project to QKV, apply RoPE, scatter into Q/K/V in place.

    Upstream rms_matmul_k_1024_2560_qkv_rope. The deep pipeline is what matters
    here: with 18 distinct per-layer weights the 5 MB projection weight is always
    a cold read, and overlapping it with compute is the whole cost of the kernel.
    `scale` and `bias` are Pi0.5's AdaRMS terms; Pi0 has none and passes None.
    """
    assert scale is None and bias is None, "Pi0 has no AdaRMS scale or shift"
    M, Kdim = x.shape
    head_dim = V.shape[1]
    num_heads = Q.shape[0] // M
    factor = _rms_factor(x, norm_factor[:M])
    kfn = _compiled(kernels.tl_qkv_gemm_rope, M=M, N=weight_qkv.shape[1], K=Kdim,
                    HEAD_DIM=head_dim, NUM_HEADS=num_heads, **_DEC_QKV)
    kfn(x, factor, weight_qkv, rope, Q.view(M, num_heads * head_dim), K, V)


def action_expert_attention(Q, K, V, mask, out, prefix_len, *, scratch=fresh_scratch):
    """out = softmax_mask0(Q @ K^T * scale) @ V, materializing the score matrix.

    Upstream matmul_k8_256_n_softmax_mask0 + matmul_k8_n_256. The fused path
    replaces this with FlashDecoding (`fused.action_expert_attention`), which
    keeps the scores in SRAM; this version stays as the readable reference and
    the reference route.

    Pi0 runs an empty prompt and has no padding, so `mask` is None and the
    prefix length arrives as the integer `prefix_len`. `out` aliases Q (both
    are the query buffer) -- safe, since the final GEMM reads its input through
    the softmaxed scores, a workspace, not Q.
    """
    assert mask is None, "Pi0 has no key mask; the prefix length is the integer"
    encoder_seq_len = prefix_len
    queries, head_dim = Q.shape
    keys = K.shape[0]
    frag_w = max(1024, 1 << (keys - 1).bit_length())

    scores_fn = _compiled(kernels.tl_matmul_abT_scale, M=queries, N=keys, K=head_dim,
                          SCALE=float(head_dim ** -0.5), **_DEC_SCORES)
    softmax_fn = _compiled(kernels.tl_softmax_mask0, Q=queries, N=keys, KEYS=keys,
                           NUM_HEADS=DECODER_HEADS, ENC_LEN=encoder_seq_len, FRAG_W=frag_w,
                           **_DEC_SOFTMAX)
    attn_v_fn = _compiled(kernels.tl_matmul, M=queries, N=head_dim, K=keys, **_DEC_ATTN_V)

    raw = scratch("attn_scores", (queries, keys), Q.dtype, Q.device)
    scores = scratch("attn_probs", (queries, keys), Q.dtype, Q.device)
    scores_fn(Q, K, raw)
    softmax_fn(raw, scores)
    attn_v_fn(scores, V, out)
    return out


def action_expert_out_proj_residual(x, weight, gate, out):
    """out += x @ weight, in place (upstream matmul_k_2048_1024_res). `gate` is Pi0.5's; None here."""
    assert gate is None, "Pi0 has no AdaRMS gate"
    M, K = x.shape
    _compiled(kernels.tl_matmul_res, M=M, N=weight.shape[1], K=K,
              **_DEC_RESIDUAL)(x, weight, out, out)
    return out


def action_expert_ffn_down_residual(x, weight, gate, out):
    """out += x @ weight, in place (upstream matmul_k_4096_1024_res). `gate` is Pi0.5's; None here."""
    assert gate is None, "Pi0 has no AdaRMS gate"
    M, K = x.shape
    _compiled(kernels.tl_matmul_res, M=M, N=weight.shape[1], K=K,
              **_DEC_RESIDUAL)(x, weight, out, out)
    return out


def action_expert_norm_gated_ffn(x, scale, gate_w, up_w, gate_b, up_b, out, norm_factor):
    """out = gelu(rms(x) @ gate_w) * (rms(x) @ up_w) (upstream rms_matmul_k_1024_4096_gate).

    `scale`, `gate_b` and `up_b` are Pi0.5's AdaRMS terms; Pi0 passes None.
    """
    assert scale is None and gate_b is None and up_b is None, "Pi0 has no AdaRMS terms"
    M, K = x.shape
    factor = _rms_factor(x, norm_factor[:M])
    _compiled(kernels.tl_scaled_gate, M=M, N=gate_w.shape[1], K=K,
              **_DEC_GATE)(x, factor, gate_w, up_w, out)
    return out


def action_expert_action_out_proj(x, weight, bias, out, norm_factor):
    """out += bias + rms(x) @ weight (upstream rms_matmul_k_1024_32_bias_res)."""
    M, K = x.shape
    factor = _rms_factor(x, norm_factor[:M])
    kfn = _compiled(kernels.tl_scaled_matmul_bias_res, M=M, N=weight.shape[1], K=K,
                    **_DEC_OUT_PROJ)
    out.copy_(kfn(x, factor, weight, bias, out))
    return out


DECODER_WRAPPERS = {
    "action_expert_state_proj": action_expert_state_proj,
    "action_expert_action_in_proj": action_expert_action_in_proj,
    "action_expert_action_mlp": action_expert_action_mlp,
    "action_expert_norm_qkv_rope": action_expert_norm_qkv_rope,
    "action_expert_attention": action_expert_attention,
    "action_expert_out_proj_residual": action_expert_out_proj_residual,
    "action_expert_ffn_down_residual": action_expert_ffn_down_residual,
    "action_expert_norm_gated_ffn": action_expert_norm_gated_ffn,
    "action_expert_action_out_proj": action_expert_action_out_proj,
}


# ---------------------------------------------------------------------------
# Vision (27 layers, LayerNorm, M = num_views * 256 = 768, hidden 1152, FFN 4304)
#
# High occupancy, so warp specialization pays off everywhere except the patch
# embedding and QKV projection. Two axes here divide no practical block size
# (4304 = 16 * 269 with 269 prime, and K=588); they run unpadded on the kernel's
# masking, same as Triton.
# ---------------------------------------------------------------------------
_VIS_PATCH = dict(BLOCK_M=64, BLOCK_N=128, BLOCK_K=64, NUM_STAGES=3, THREADS=128)
_VIS_NORM = dict(BLOCK_M=1, BLOCK_K=1152, THREADS=128)
_VIS_QKV = dict(BLOCK_M=128, BLOCK_N=64, BLOCK_K=64, NUM_STAGES=2, THREADS=128)
_VIS_OUT_PROJ = dict(BLOCK_M=64, BLOCK_N=128, BLOCK_K=128, NUM_STAGES=4, THREADS=256)
_VIS_FFN_UP = dict(BLOCK_M=128, BLOCK_N=128, BLOCK_K=64, NUM_STAGES=4, THREADS=256)
_VIS_FFN_DOWN = dict(BLOCK_M=64, BLOCK_N=128, BLOCK_K=128, NUM_STAGES=3, THREADS=128)

VISION_TOKENS = 256
VISION_DIM = 1152
VISION_FFN = 4304
PATCH_FEATURES = 3 * 14 * 14


def _vision_layer_norm(x, norm_w, norm_b, out):
    """LayerNorm over the feature axis, written into `out`."""
    M, K = x.shape
    _compiled(kernels.tl_layer_norm, M=M, K=K, EPS=1e-5, **_VIS_NORM)(x, norm_w, norm_b, out)
    return out


def _vision_norm_workspace(scratch, x2):
    """The normalized activation the two pre-norm GEMMs consume: workspace of this
    backend, allocated once through the runner's allocator, not a graph buffer."""
    return scratch("vision_norm", tuple(x2.shape), x2.dtype, x2.device)


def vision_encoder_patch_embed(images, patch_w, patch_b, pos_emb, out):
    """Patchify, project, add bias and the positional embedding (upstream conv2d_embed_n256_1152_res).

    The 14x14x3 convolution is a GEMM over flattened patches; the positional
    embedding is a 256-row residual broadcast across views by the kernel's modulo.
    """
    views = images.shape[0]
    M = VISION_TOKENS * views
    patches = (images.view(views, 16, 14, 16, 14, 3).permute(0, 1, 3, 2, 4, 5)
               .contiguous().view(M, PATCH_FEATURES))
    kfn = _compiled(kernels.tl_matmul_bias_res_mod, M=M, N=VISION_DIM, K=PATCH_FEATURES,
                    I_MOD=VISION_TOKENS, **_VIS_PATCH)
    kfn(patches, patch_w.reshape(PATCH_FEATURES, VISION_DIM), patch_b, pos_emb, out.view(M, VISION_DIM))
    return out


def vision_encoder_norm_qkv(x, norm_w, norm_b, qkv_w, qkv_b, out, *, scratch=fresh_scratch):
    """LayerNorm then the packed QKV projection (upstream layer_norm_QKV_matmul_n256_1152_3456_bias)."""
    M = x.shape[0] * VISION_TOKENS
    hidden = qkv_w.shape[1]
    x2 = x.view(M, VISION_DIM)
    x_norm2 = _vision_layer_norm(x2, norm_w, norm_b, _vision_norm_workspace(scratch, x2))
    _compiled(kernels.tl_matmul_bias_nows, M=M, N=hidden, K=VISION_DIM,
              **_VIS_QKV)(x_norm2, qkv_w, qkv_b, out.view(M, hidden))
    return out


def vision_encoder_out_proj_residual(x, weight, bias, res, out):
    """out = attn @ weight + bias + res (upstream matmul_n256_1152_1152_bias_res).

    Collapses upstream's masked/unmasked and split-K branches into one
    fp32-accumulating GEMM. `res` and `out` alias the same buffer.
    """
    M = x.shape[0] * VISION_TOKENS
    kfn = _compiled(kernels.tl_matmul_bias_res, M=M, N=VISION_DIM, K=VISION_DIM, **_VIS_OUT_PROJ)
    kfn(x.reshape(M, VISION_DIM), weight, bias, res.view(M, VISION_DIM), out.view(M, VISION_DIM))
    return out


def vision_encoder_norm_ffn_up(x, norm_w, norm_b, weight, bias, out, *, scratch=fresh_scratch):
    """LayerNorm then the GELU feed-forward expansion (upstream layer_norm_matmul_..._bias_gelu)."""
    M = x.shape[0] * VISION_TOKENS
    x2 = x.view(M, VISION_DIM)
    x_norm2 = _vision_layer_norm(x2, norm_w, norm_b, _vision_norm_workspace(scratch, x2))
    _compiled(kernels.tl_matmul_bias_gelu, M=M, N=VISION_FFN, K=VISION_DIM,
              **_VIS_FFN_UP)(x_norm2, weight, bias, out.view(M, VISION_FFN))
    return out


def vision_encoder_ffn_down_residual(x, weight, bias, res, out):
    """out = hidden @ weight + bias + res (upstream matmul_n256_4304_1152_bias_res)."""
    M = x.shape[0] * VISION_TOKENS
    kfn = _compiled(kernels.tl_matmul_bias_res, M=M, N=VISION_DIM, K=VISION_FFN, **_VIS_FFN_DOWN)
    kfn(x.reshape(M, VISION_FFN), weight, bias, res.view(M, VISION_DIM), out.view(M, VISION_DIM))
    return out


VISION_WRAPPERS = {
    "vision_encoder_patch_embed": vision_encoder_patch_embed,
    "vision_encoder_attention": _attention.vision_encoder_attention,
    "vision_encoder_norm_qkv": vision_encoder_norm_qkv,
    "vision_encoder_out_proj_residual": vision_encoder_out_proj_residual,
    "vision_encoder_norm_ffn_up": vision_encoder_norm_ffn_up,
    "vision_encoder_ffn_down_residual": vision_encoder_ffn_down_residual,
}


# ---------------------------------------------------------------------------
# Encoder (18 layers, RMSNorm, M = encoder_seq_len, hidden 2048, FFN 16384)
#
# Same high-occupancy regime as vision: warp specialization on throughout. The
# gated FFN here is the single largest kernel in the model.
# ---------------------------------------------------------------------------
_ENC_PROJ_NORM = dict(BLOCK_M=1, BLOCK_K=1152, THREADS=128)
_ENC_PROJ = dict(BLOCK_M=128, BLOCK_N=128, BLOCK_K=128, NUM_STAGES=3, THREADS=256)
_ENC_RMS = dict(BLOCK_M=1, BLOCK_K=128, THREADS=128)
_ENC_QKV = dict(BLOCK_M=128, BLOCK_N=128, BLOCK_K=64, NUM_STAGES=4, THREADS=256)
_ENC_ROPE = dict(BLOCK_M=64, BLOCK_PAIR=128, THREADS=256)
_ENC_OUT_PROJ = dict(BLOCK_M=128, BLOCK_N=128, BLOCK_K=64, NUM_STAGES=4, THREADS=256, SWIZZLE=0)
_ENC_GATE = dict(BLOCK_M=128, BLOCK_N=128, BLOCK_K=128, NUM_STAGES=2, THREADS=256, SWIZZLE=8)
_ENC_FFN_DOWN = dict(BLOCK_M=128, BLOCK_N=128, BLOCK_K=128, NUM_STAGES=3, THREADS=256, SWIZZLE=8)

ENCODER_DIM = 2048


def llm_backbone_projector(x, norm_w, norm_b, proj_w, proj_b, out, x_norm):
    """Final vision LayerNorm then the projection into encoder width (upstream layer_norm_matmul_n256_1152_2048_bias)."""
    M = x.shape[0] * VISION_TOKENS
    x2, x_norm2 = x.view(M, VISION_DIM), x_norm.view(M, VISION_DIM)
    _compiled(kernels.tl_layer_norm, M=M, K=VISION_DIM, EPS=1e-5,
              **_ENC_PROJ_NORM)(x2, norm_w, norm_b, x_norm2)
    _compiled(kernels.tl_matmul_bias, M=M, N=ENCODER_DIM, K=VISION_DIM,
              **_ENC_PROJ)(x_norm2, proj_w, proj_b, out[:M])
    return out


def llm_backbone_norm_qkv_rope(x, weight_qkv, rope, Q, K, V, x_norm, *, scratch=fresh_scratch):
    """RMSNorm, QKV projection, then RoPE scattered into Q/K/V (upstream rms_matmul_n_2048_2560_qkv_rope).

    Three kernels rather than the decoder's one: the encoder normalizes x before
    the GEMM instead of folding a factor into it, and rounds to bf16 before
    rotating. Both orderings match upstream and are not interchangeable.
    """
    M, Kdim = x.shape
    N = weight_qkv.shape[1]
    head_dim = V.shape[1]
    num_heads = Q.shape[0] // M

    _compiled(kernels.tl_rms_norm, M=M, K=Kdim, **_ENC_RMS)(x, x_norm[:M])
    projected = scratch("encoder_qkv", (M, N), x.dtype, x.device)
    _compiled(kernels.tl_matmul_ws, M=M, N=N, K=Kdim, **_ENC_QKV)(x_norm[:M], weight_qkv, projected)
    _compiled(kernels.tl_rope_scatter_bf16, M=M, N=N, HEAD_DIM=head_dim, NUM_HEADS=num_heads,
              **_ENC_ROPE)(projected, rope, Q.view(M, num_heads * head_dim), K, V)


def llm_backbone_out_proj_residual(x, weight, out):
    """out += attn @ weight, in place (upstream matmul_n_2048_2048_res)."""
    M, K = x.shape
    _compiled(kernels.tl_matmul_res_ws, M=M, N=weight.shape[1], K=K,
              **_ENC_OUT_PROJ)(x, weight, out, out)
    return out


def llm_backbone_norm_gated_ffn(x, gate_w, up_w, out, x_norm):
    """RMSNorm then the gated feed-forward (upstream rms_matmul_n_2048_16384_gate)."""
    M, K = x.shape
    _compiled(kernels.tl_rms_norm, M=M, K=K, **_ENC_RMS)(x, x_norm[:M])
    _compiled(kernels.tl_matmul_gate, M=M, N=gate_w.shape[1], K=K,
              **_ENC_GATE)(x_norm[:M], gate_w, up_w, out[:M])
    return out


def llm_backbone_ffn_down_residual(x, weight, out):
    """out += hidden @ weight, in place (upstream matmul_n_16384_2048_res).

    K=16384 makes the weight far larger than L2, so this one runs with the L2
    swizzle enabled.
    """
    M, K = x.shape
    _compiled(kernels.tl_matmul_res_ws, M=M, N=weight.shape[1], K=K,
              **_ENC_FFN_DOWN)(x, weight, out, out)
    return out


def llm_backbone_attention(Q, K, V, scale, mask, out):
    """Multi-query attention over the prefix, written into `out` (torch chain).

    Pi0's prefix has no padding, so `mask` is None; `out` is (seq*heads,
    head_dim), which the graph reads as (seq, heads*head_dim).
    """
    assert mask is None, "Pi0 has no key mask"
    _attention.llm_backbone_attention(Q, K, V, scale, out)
    return out


def llm_backbone_embed_prompt(token_ids, table, scale, out):
    """out = table: Pi0's prompt is fixed at load time, so its embeddings are a
    checkpoint tensor copied into the language rows of the prefix. Pi0.5 gathers
    the same rows from a vocabulary table by token id; here ids and scale are None."""
    assert token_ids is None and scale is None, "Pi0's prompt embeddings are precomputed"
    out.copy_(table)
    return out


ENCODER_WRAPPERS = {
    "llm_backbone_projector": llm_backbone_projector,
    "llm_backbone_embed_prompt": llm_backbone_embed_prompt,
    "llm_backbone_attention": llm_backbone_attention,
    "llm_backbone_norm_qkv_rope": llm_backbone_norm_qkv_rope,
    "llm_backbone_out_proj_residual": llm_backbone_out_proj_residual,
    "llm_backbone_norm_gated_ffn": llm_backbone_norm_gated_ffn,
    "llm_backbone_ffn_down_residual": llm_backbone_ffn_down_residual,
}

ALL_WRAPPERS = {**VISION_WRAPPERS, **ENCODER_WRAPPERS, **DECODER_WRAPPERS}

#: The call sites this backend implements.
NAMES = frozenset(ALL_WRAPPERS)

#: Wrappers that request workspace and take the runner's allocator.
_NEEDS_SCRATCH = ("action_expert_attention", "llm_backbone_norm_qkv_rope",
                  "vision_encoder_norm_qkv", "vision_encoder_norm_ffn_up")

#: Pi0's two extension ops beyond the standard vocabulary: the state token's
#: projection and the second action MLP, both plain bias GEMMs.
OPS = (
    OpSpec("action_expert_state_proj", ("x", "weight", "bias", "out"), outputs=("out",),
           weights=("weight", "bias"), flops=gemm("x", "weight")),
    OpSpec("action_expert_action_mlp", ("x", "weight", "bias", "out"), outputs=("out",),
           weights=("weight", "bias"), flops=gemm("x", "weight")),
)
ROUTE_CONSTRAINTS: tuple = ()


def make_wrappers(scratch, selected_names=None) -> dict:
    """The wrappers of `selected_names` (default: all), bound to `scratch`."""
    names = NAMES if selected_names is None else set(selected_names)
    unknown = names - NAMES
    if unknown:
        raise KeyError(f"tilelang backend does not implement {sorted(unknown)}")
    return {name: (partial(ALL_WRAPPERS[name], scratch=scratch) if name in _NEEDS_SCRATCH
                   else ALL_WRAPPERS[name])
            for name in names}
